export const siteConfig = {
  name: "M. Daffa Raihan Akbar | Developer Portfolio Template",
  authorName: "M. Daffa Raihan Akbar",
  username: "daffakbar13",
  description:
    "M. Daffa Raihan Akbar's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://nbarkiya.xyz",
  links: {
    twitter: "https://x.com/daffakbar13",
    github: "https://github.com/daffakbar13",
  },
  ogImage: "https://nbarkiya.xyz/daffa2.png",
  iconIco:
    "https://api.logo.com/api/v2/images?design=lg_DmWBUZNybLLarqDlJ0&u=3355c4fae3283be15e48aec23df7125c97369e64f5193638e0d65ec1f1ca6e96&width=500&height=400&margins=100&fit=contain&format=webp&quality=60&tightBounds=true",
  logoIcon:
    "https://api.logo.com/api/v2/images?design=lg_DmWBUZNybLLarqDlJ0&u=3355c4fae3283be15e48aec23df7125c97369e64f5193638e0d65ec1f1ca6e96&width=500&height=400&margins=100&fit=contain&format=webp&quality=60&tightBounds=true",
  keywords: [
    "M. Daffa Raihan Akbar",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
